import { useParams, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowLeft, ChevronRight, Download, Share2, Clock, Users } from 'lucide-react'
import { SourcePill } from '@/components/shared/SourcePill'
import { ConfidenceBadge } from '@/components/shared/ConfidenceBadge'

const sections = [
  {
    title: 'How the Backend is structured',
    summary: 'The backend is a Node.js + TypeScript modular monolith deployed on Cloud Run. Modules communicate through typed interfaces — never directly across module boundaries. The graph layer owns its own Postgres schema namespace.',
    sources: 3, updated: '2d ago',
  },
  {
    title: 'The 5 most important architecture decisions',
    decisions: [
      { title: 'Modular monolith before microservices', date: 'Feb 28', confidence: 0.96, source: 'notion' as const },
      { title: 'JWT auth replaces session tokens',       date: 'Mar 19', confidence: 0.91, source: 'slack'  as const },
      { title: 'pgvector over Pinecone',                 date: 'Apr 18', confidence: 0.85, source: 'meeting' as const },
      { title: 'Drizzle ORM over Prisma',                date: 'Feb 10', confidence: 0.79, source: 'slack'  as const },
      { title: 'Cursor-based pagination',                date: 'Apr 24', confidence: 0.88, source: 'github'  as const },
    ],
  },
  {
    title: 'What was considered and rejected',
    rejected: [
      { option: 'Microservices from day one', reason: 'Too much operational overhead at current headcount. Revisit at 1M events/day.' },
      { option: 'Pinecone for vector storage', reason: 'Cost analysis showed 60% savings with pgvector at current scale.' },
      { option: 'Prisma ORM',                  reason: 'Performance benchmarks favoured Drizzle. TypeScript-native design preferred.' },
    ],
  },
  {
    title: 'People to know on this team',
    people: [
      { name: 'Alex Kumar',   role: 'Owns billing and payments',     initials: 'AK' },
      { name: 'Sarah Chen',   role: 'Owns auth and API gateway',     initials: 'SC' },
      { name: 'Priya Nair',   role: 'Owns infra and deployments',   initials: 'PN' },
    ],
  },
  {
    title: 'Open questions on this team',
    questions: [
      { q: 'Stripe webhook idempotency — edge cases unresolved', last: '3d ago' },
      { q: 'Extraction trigger threshold for ingestion service',  last: '1w ago' },
      { q: 'HIPAA path for enterprise tier — legal review pending', last: '2w ago' },
    ],
  },
]

export default function PackDetail() {
  const { id } = useParams()

  return (
    <div className="px-8 py-7 max-w-[780px] mx-auto">
      {/* Back */}
      <Link to="/app/onboarding-packs" className="inline-flex items-center gap-1.5 text-[12.5px] text-white/30 hover:text-white/60 transition-colors mb-7">
        <ArrowLeft className="w-3.5 h-3.5" />
        Onboarding Packs
      </Link>

      {/* Header */}
      <div className="flex items-start justify-between mb-8">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/30 to-violet-500/30 border border-white/[0.08] flex items-center justify-center">
            <span className="text-[14px] font-bold text-white">AK</span>
          </div>
          <div>
            <h1 className="text-[20px] font-semibold text-white mb-0.5">Alex Kumar — Backend Team</h1>
            <div className="flex items-center gap-3 text-[12px] text-white/30">
              <span className="flex items-center gap-1"><Clock className="w-3 h-3" />Joined 2 days ago</span>
              <span>·</span>
              <span className="flex items-center gap-1"><Users className="w-3 h-3" />7 decisions · 3 sources</span>
            </div>
          </div>
        </div>
        <div className="flex gap-2">
          <button className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl border border-white/[0.08] bg-white/[0.03] text-[12.5px] text-white/45 hover:text-white/80 hover:border-white/[0.14] hover:bg-white/[0.06] transition-all">
            <Share2 className="w-3.5 h-3.5" />
            Share
          </button>
          <button className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl border border-white/[0.08] bg-white/[0.03] text-[12.5px] text-white/45 hover:text-white/80 hover:border-white/[0.14] hover:bg-white/[0.06] transition-all">
            <Download className="w-3.5 h-3.5" />
            Export
          </button>
        </div>
      </div>

      <p className="text-[13.5px] text-white/40 leading-relaxed mb-8 pb-8 border-b border-white/[0.06]">
        Generated by Dyson from <span className="text-white/60">142 events</span> across Slack, GitHub, and Notion.
        This pack covers the 7 decisions that shaped the Backend team's current architecture, the people who made them,
        the trade-offs considered, and 3 open questions still on the team's plate.
      </p>

      {/* Sections */}
      <div className="space-y-8">
        {sections.map((section, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.08 }}
            className="rounded-xl border border-white/[0.07] bg-[#0F0F17] overflow-hidden"
          >
            <div className="flex items-center gap-3 px-5 py-4 border-b border-white/[0.06]">
              <span className="text-[10px] font-mono font-bold text-primary bg-primary/10 border border-primary/20 w-5 h-5 rounded flex items-center justify-center flex-shrink-0">{i + 1}</span>
              <h2 className="text-[14px] font-semibold text-white/85">{section.title}</h2>
            </div>

            <div className="px-5 py-5">
              {/* Summary text */}
              {'summary' in section && (
                <p className="text-[13.5px] text-white/50 leading-[1.7]">{section.summary}</p>
              )}

              {/* Decisions */}
              {'decisions' in section && (
                <div className="space-y-2">
                  {section.decisions.map((d, j) => (
                    <div key={j} className="flex items-center gap-3 p-3 rounded-lg hover:bg-white/[0.03] transition-colors group cursor-pointer">
                      <div className="w-1.5 h-1.5 rounded-full bg-citation/60 flex-shrink-0" />
                      <span className="flex-1 text-[13px] text-white/65 group-hover:text-white/85 transition-colors">{d.title}</span>
                      <span className="text-[11px] font-mono text-white/25">{d.date}</span>
                      <SourcePill source={d.source} />
                      <ConfidenceBadge confidence={d.confidence} />
                    </div>
                  ))}
                </div>
              )}

              {/* Rejected */}
              {'rejected' in section && (
                <div className="space-y-3">
                  {section.rejected.map((r, j) => (
                    <div key={j} className="p-4 rounded-lg bg-white/[0.02] border border-white/[0.05]">
                      <p className="text-[13px] font-medium text-white/50 line-through mb-1.5">{r.option}</p>
                      <p className="text-[12.5px] text-white/35 leading-relaxed">{r.reason}</p>
                    </div>
                  ))}
                </div>
              )}

              {/* People */}
              {'people' in section && (
                <div className="space-y-3">
                  {section.people.map((p, j) => (
                    <div key={j} className="flex items-center gap-3 p-3 rounded-lg hover:bg-white/[0.03] transition-colors cursor-pointer group">
                      <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary/30 to-violet-500/30 border border-primary/20 flex items-center justify-center flex-shrink-0">
                        <span className="text-[10px] font-bold text-primary">{p.initials}</span>
                      </div>
                      <div className="flex-1">
                        <p className="text-[13px] font-medium text-white/75 group-hover:text-white/95 transition-colors">{p.name}</p>
                        <p className="text-[11.5px] text-white/30">{p.role}</p>
                      </div>
                      <ChevronRight className="w-3.5 h-3.5 text-white/15 group-hover:text-primary transition-colors" />
                    </div>
                  ))}
                </div>
              )}

              {/* Questions */}
              {'questions' in section && (
                <div className="space-y-2.5">
                  {section.questions.map((q, j) => (
                    <div key={j} className="flex items-start gap-3 p-3.5 rounded-lg border border-white/[0.05] bg-white/[0.02] hover:border-white/[0.09] transition-colors cursor-pointer group">
                      <div className="w-1.5 h-1.5 rounded-full bg-orange-400/60 mt-1.5 flex-shrink-0" />
                      <p className="flex-1 text-[13px] text-white/55 group-hover:text-white/75 transition-colors leading-relaxed">{q.q}</p>
                      <span className="text-[10px] font-mono text-white/20 flex-shrink-0 mt-0.5">{q.last}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-8 pt-6 border-t border-white/[0.06] text-center">
        <p className="text-[11.5px] text-white/20">
          Generated by Dyson · {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>
      </div>
    </div>
  )
}
